### ISSUE TITLE
Bug on loading

### ISSUE THREAD

**Issue by Boomer-1** [LinoxGH/MoreTools#16]
## Description (Required)

As my server was restarting I saw an error relating to More Tools. I don't know what the error is or what it affects, other than what I could read. something about the crescent hammer
[latest.log](https://github.com/LinoxGH/MoreTools/files/5817860/latest.log)

## Steps to reproduce the Issue (Required)

Loaded my server, the error popped up before I was able to even login to the server.

## Expected behavior (Required)

don't know as I can't tell you what the error is

## Server Log / Error Report

[latest.log](https://github.com/LinoxGH/MoreTools/files/5817863/latest.log)

## Environment (Required)

 - Minecraft Version: 1.16.3
 - CS-CoreLib Version: dev 92
 - Slimefun Version: dev 784
 - Plugin Version: dev 9

**Comment by LinoxGH** [comment]
Same as #15 which I think I fixed.
