### ISSUE TITLE
Slimefun Build#820 Changes to BlockBreakHandler broke the addon.

### ISSUE THREAD

**Issue by Boomer-1** [LinoxGH/MoreTools#20]
## Description (Required)

I saw this error in the console as it loaded. From what I have heard it hit a few plugins. 

## Server Log / Error Report

https://pastebin.com/6Epi5duK

## Environment (Required)

 - Minecraft Version: 1.16.15
 - CS-CoreLib Version: removed
 - Slimefun Version: dev 820
 - Plugin Version:  dev 10

**Comment by mrcoffee1026** [comment]
Persistent issue confirmed   MoreTools vDEV - 10, Slimefun vDEV 912

**Comment by LinoxGH** [comment]
Fixed the issue. I did not test the item in 1.17 or RC-26 but i fixed all compile-time errors and startup errors.
