### ISSUE TITLE
error console

### ISSUE THREAD

**Issue by ArrozElManko** [LinoxGH/MoreTools#21]
## Description (Required)
every time I start my server does not load the addon and an error appears in the console

## Expected behavior (Required)
error

## Server Log / Error Report
https://hatebin.com/vnlpbkbqgd

## Environment (Required)
https://imgur.com/5mjRisM

**Comment by bobhenl** [comment]
Yeah it is not working again @LinoxGH  :D

**Comment by LinoxGH** [comment]
This is the same as #20 so closing this.
