### ISSUE TITLE
Fails to load.

### ISSUE THREAD

**Issue by MagmaSlime123** [LinoxGH/MoreTools#24]
## Description (Required)
Plugin fails to load.

## Steps to reproduce the Issue (Required)
Use the plugin.

## Expected behavior (Required)
The plugin to load.

## Server Log / Error Report
https://pastebin.com/VQRusVM7

## Environment (Required)
![2022-04-18_13 35 07](https://user-images.githubusercontent.com/51277766/163873752-d91cff6d-eb33-4f4f-8a48-78a32f8b2699.png)
![2022-04-18_13 35 09](https://user-images.githubusercontent.com/51277766/163873756-1a0a1d22-ef7f-4db9-9c45-db519ffb42f3.png)

And MoreTools - DEV 10 (git 660e2), since it won't show up in /sf versions due to this issue.

**Comment by LinoxGH** [comment]
DEV 10 is outdated, that's why it doesnt load.
