### ISSUE TITLE
[Feature request] Automatically update config

### ISSUE THREAD

**Issue by bobhenl** [LinoxGH/MoreTools#6]
Hi, could you please add way to automatically update config like in other plugins?

This is not so good solution [15:35:04] [Server thread/ERROR]: [MoreTools] Your config.yml file is outdated, resetting it and then disabling the plugin! Please restart.

**Comment by LinoxGH** [comment]
> Hi, could you please add way to automatically update config like in other plugins?
> 
> This is not so good solution [15:35:04] [Server thread/ERROR]: [MoreTools] Your config.yml file is outdated, resetting it and then disabling the plugin! Please restart.

I'll look into it for the next build.

**Comment by LinoxGH** [comment]
Done.
