### ISSUE TITLE
Players can not place any blocks

### ISSUE THREAD

**Issue by NCBPFluffyBear** [LinoxGH/MoreTools#9]
## Description (Required)
Latest build of MoreTools prevents any Slimefun block from being placed

## Steps to reproduce the Issue (Required)
Install MoreTools, try placing any Slimefun block. Blocks from addons have the same problem too.

## Expected behavior (Required)
Blocks should be able to be placed

## Server Log / Error Report
No errors appear in console

## Environment (Required)

![image](https://user-images.githubusercontent.com/31554056/93655290-15b2f500-f9e8-11ea-99be-f12bcf049572.png)

(I know theres a modified LX build in there, it isnt the problem, this has happened on another server too.)

**Comment by NCBPFluffyBear** [comment]
Checked with MoreTools build 4, no problems there. (It has to do with latest)

**Comment by LinoxGH** [comment]
Fixed.
